# Generated by Django 3.2.7 on 2021-11-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211103_1554'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
