# Generated by Django 3.2.7 on 2021-11-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='product',
            new_name='products',
        ),
    ]
