# Generated by Django 3.2.7 on 2021-11-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_rename_product_batch_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='products',
        ),
    ]
