# Generated by Django 3.2.7 on 2021-11-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_batch'),
        ('batches', '0004_remove_batch_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
