# Generated by Django 3.2.7 on 2021-11-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
    ]
