# Generated by Django 3.2.7 on 2021-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(max_length=100, null=True, verbose_name='Url da foto'),
        ),
    ]
