# Generated by Django 3.2.7 on 2021-11-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_remove_batch_products'),
        ('products', '0005_auto_20211103_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
    ]
