# Generated by Django 3.2.7 on 2021-11-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='batch',
        ),
    ]
