# Generated by Django 3.2.7 on 2021-10-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('auctioneer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auctioneer', to='users.user')),
            ],
        ),
    ]
