# Generated by Django 3.2.7 on 2021-10-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('users', '0001_initial'),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='users.user'),
        ),
    ]
