# Generated by Django 3.2.7 on 2021-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
