# Generated by Django 3.2.7 on 2021-10-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20211022_2011'),
        ('users', '0003_alter_user_password'),
        ('auctions', '0003_alter_auction_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auctioneer_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.AddField(
            model_name='auction',
            name='batch',
            field=models.OneToOneField(default=0.0006927263730826323, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='batches.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Lucro'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
