# Generated by Django 3.2.7 on 2021-10-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211022_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='batch',
            new_name='batch_id',
        ),
    ]
