# Generated by Django 3.2.7 on 2021-10-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
        ('auctions', '0005_rename_batch_auction_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctioneer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioned_by', to='users.user'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to='users.user'),
        ),
    ]
