# Generated by Django 3.2.7 on 2021-10-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20211022_2011'),
        ('auctions', '0006_auto_20211022_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='batch_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
    ]
