# Generated by Django 3.2.7 on 2021-10-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211022_2059'),
        ('auctions', '0008_auto_20211022_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctioneer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioned_by', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Lucro'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to='users.user'),
        ),
    ]
