# Generated by Django 3.2.7 on 2021-10-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
    ]
