# Generated by Django 3.2.7 on 2021-10-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='batch_id',
        ),
    ]
