# Generated by Django 3.2.7 on 2021-10-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20211022_2011'),
        ('products', '0003_remove_product_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(max_length=100, null=True, verbose_name='Foto'),
        ),
    ]
