# Generated by Django 3.2.7 on 2021-10-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_auto_20211022_2059'),
        ('products', '0004_auto_20211022_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
    ]
