# Generated by Django 3.2.7 on 2021-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20211112_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('Faturamento', 'Faturamento'), ('Desempenho', 'Desempenho')], default='Faturamento', max_length=11, verbose_name='Tipo de relatório'),
        ),
    ]
