# Generated by Django 3.2.7 on 2021-11-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='value',
        ),
    ]
