# Generated by Django 3.2.7 on 2021-11-25 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_product_picture'),
        ('batches', '0003_alter_batch_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='Produtos'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
