# Generated by Django 3.2.7 on 2021-11-04 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0005_batch_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de fim')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor mínimo')),
                ('min_bid_increase_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Aumento mínimo por lance')),
                ('register_fee', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor mínimo')),
                ('sale_fee', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor mínimo')),
                ('register_fee_paid', models.BooleanField(default=False, verbose_name='Taxa de Registro Paga')),
                ('sale_fee_paid', models.BooleanField(verbose_name='Taxa da Venda Paga')),
                ('auctioneer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioned_by', to=settings.AUTH_USER_MODEL)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
