# Generated by Django 3.2.7 on 2021-11-04 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_batch_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Auction',
        ),
    ]
