# Generated by Django 3.2.7 on 2021-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_batch_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auctioneer_id',
            new_name='auctioneer',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='winner_id',
            new_name='winner',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='sale_fee',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='sale_fee_paid',
        ),
        migrations.AddField(
            model_name='auction',
            name='buy_fee',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Taxa de Compra'),
        ),
        migrations.AddField(
            model_name='auction',
            name='buy_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Taxa da Compra Paga'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='register_fee',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Taxa de Registro'),
        ),
    ]
