# Generated by Django 3.2.7 on 2021-11-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='buyer_id',
            new_name='buyer',
        ),
    ]
