# Generated by Django 3.2.7 on 2021-11-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211104_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_bid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Lance Vencedor'),
        ),
    ]
