# Generated by Django 3.2.7 on 2021-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[('Não iniciado', 'Not Started'), ('Ocorrendo', 'Running'), ('Finalizado', 'Finished'), ('Inválido', 'Invalid'), ('Cancelado', 'Canceled')], default='Não iniciado', max_length=50, verbose_name='Tipo de relatório'),
        ),
    ]
