# Generated by Django 3.2.7 on 2021-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_winner_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='winner_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_bid_id',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True),
        ),
    ]
