# Generated by Django 3.2.7 on 2021-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211104_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Data e Horário'),
        ),
    ]
