# Generated by Django 3.2.7 on 2021-11-05 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de fim')),
                ('winner_bid', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Lance Vencedor')),
                ('winner_bid_id', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor inicial')),
                ('min_bid_increase_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Aumento mínimo por lance')),
                ('register_fee', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Taxa de Registro')),
                ('buy_fee', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Taxa de Compra')),
                ('register_fee_paid', models.BooleanField(default=False, verbose_name='Taxa de Registro Paga')),
                ('buy_fee_paid', models.BooleanField(default=False, verbose_name='Taxa da Compra Paga')),
                ('auctioneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioned_by', to=settings.AUTH_USER_MODEL)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('datetime', models.DateTimeField(null=True, verbose_name='Data e Horário')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
