# Generated by Django 3.2.7 on 2021-11-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_remove_batch_value'),
        ('auctions', '0005_auto_20211119_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batches.batch', verbose_name='Lote'),
        ),
    ]
