# Generated by Django 3.2.7 on 2021-11-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[('Não iniciado', 'Not Started'), ('Ocorrendo', 'Running'), ('Finalizado', 'Finished'), ('Não atingiu o valor de reserva', 'Invalid'), ('Cancelado', 'Canceled')], default='Não iniciado', max_length=50, verbose_name='Tipo de relatório'),
        ),
    ]
