# Generated by Django 3.2.7 on 2021-10-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
    ]
