# Generated by Django 3.2.7 on 2021-10-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211022_2059'),
        ('users', '0004_auto_20211022_2059'),
        ('bids', '0003_alter_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='buyer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Valor'),
        ),
    ]
