# Generated by Django 3.2.7 on 2021-10-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211022_2100'),
        ('bids', '0004_auto_20211022_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auction'),
        ),
    ]
