# Generated by Django 3.2.7 on 2021-10-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211022_2059'),
        ('batches', '0002_auto_20211022_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='payed',
        ),
        migrations.AddField(
            model_name='batch',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Taxa'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='min_bid_increase_value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Aumento mínimo por lance'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Valor mínimo'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='register_fee',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Taxa de registro'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='reserve_value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='seller_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='sequential_number',
            field=models.CharField(default='', max_length=50, verbose_name='Número sequencial'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15, verbose_name='Valor'),
        ),
    ]
