# Generated by Django 3.2.7 on 2021-11-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Figura'),
        ),
    ]
